### ISSUE TITLE
Missing Answers

### ISSUE THREAD

**Issue by cheetahskita** [learn-co-curriculum/truthiness-code-challenge#15]
Within the Learn.co website, this code challenge is a 4-question quiz. However, question number three has no options to choose and no submit button. Therefore, the quiz cannot be completed. 
![capture2](https://cloud.githubusercontent.com/assets/19696738/15985573/62f530ae-2fc0-11e6-80af-13bd0f28960f.PNG)
.

**Comment by AnnJohn** [comment]
this should be fixed now. Thanks.
