### ISSUE TITLE
Missing Answer Options

### ISSUE THREAD

**Issue by nscarlyon** [learn-co-curriculum/truthiness-code-challenge#19]
Question #3 (Take a look at the method using_truthiness below. What value(s) for ? will make using_truthiness return false?)  has no options to choose as an answer. Because of this, I was not able to click 'submit' quiz, since the quiz was considered incomplete. I answered all the other questions and then clicked 'next lesson'.

**Comment by AnnJohn** [comment]
this should be fixed now. Thanks.
