### ISSUE TITLE
check windows can't be selected

### ISSUE THREAD

**Issue by codingkasia** [learn-co-curriculum/truthiness-code-challenge#25]
you can't select anything

**Comment by sgharms** [comment]
Hi there! This request sounds like an improvement to the Learn platform.
[Raising issues on GitHub][issues] should be reserved for problems with the
curriculum itself (doesn't work, throws a Ruby error, etc.)

Our product team loves to hear about our Learners' innovative interface
improvements. You can reach them at support@learn.co. Alternatively, if Learn
is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try
to discern a proper path to resolution.

[issues]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson

Thanks! :blue_heart:

**Comment by codingkasia** [comment]
oh sorry. I understand. thanks for responding!

**Comment by sgharms** [comment]
@codingkasia Don't worry! We love it when our students drive us to a better product be it technical or curricular! 💙
