### ISSUE TITLE
Just a double check

### ISSUE THREAD

**Issue by amy-l-hedges** [learn-co-curriculum/truthiness-code-challenge#26]
For the final question, "What value(s) for ? will make using_truthiness return true?
def using_truthiness
  7 > 8 || ?
end"

Wouldn't "7" be a possible correct answer since the truthiness of an integer by itself is true?

**Comment by morgvanny** [comment]
While 7 is truthy, it doesn't literally return true. It returns literally 7. So 7 > 8 || 7 will return 7, rather than true.  If it was 7 > 8 || !!7 then that would be true. So !!7 would be a possible correct answer, but just 7 isn't correct.
