### ISSUE TITLE
There is an issue with question no.4

### ISSUE THREAD

**Issue by namidao** [learn-co-curriculum/truthiness-code-challenge#27]
What value(s) for ? will make using_truthiness return true?
def using_truthiness
  7 > 8 || ?
end

I chose a. 7> 6 and b.7 
but 7 gives me an issue. I think it's a website bug that needs to be fixed.
Thanks

**Comment by morgvanny** [comment]
you can try it out in irb. 7 > 8 || 7 > 6 will return true, which is what is wanted, while 7 > 8 || 7 will actually just return 7. While 7 is truthy, it's not literally `true` which is what we want the method to return on question no.4
