### ISSUE TITLE
Unable to select answers

### ISSUE THREAD

**Issue by ScottDenton** [learn-co-curriculum/truthiness-code-challenge#30]
Hello, 

I am unable to select any answers for the quiz (either right or wrong answers) and hitting submit without any options selected just shows the correct answers.

**Comment by sgharms** [comment]
This worked fine for me. For each question: select the appropriate answer(s). Then at the end I submitted the lesson and now can go to next lesson. If this problem persists, please visit the following:

http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
