### ISSUE TITLE
Check boxes do not check

### ISSUE THREAD

**Issue by disarrangedorder** [learn-co-curriculum/truthiness-code-challenge#31]
clicking on checkboxes doesn't show checks

**Comment by sgharms** [comment]
[Raising issues on GitHub][raise] should be reserved for problems with
the curriculum itself (doesn't work, throws a Ruby error, etc.) Alternatively, if Learn
is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
