### ISSUE TITLE
I can't check the boxes in the quiz.

### ISSUE THREAD

**Issue by wilcook** [learn-co-curriculum/truthiness-code-challenge#32]
Impossible to answer the questions, as I can't mark any of the check boxes.

**Comment by sgharms** [comment]
Hi there! This request sounds like an improvement to the Learn platform.

Our product team loves to hear about our Learners' innovative interface
improvements. You can reach them at support@learn.co. Alternatively, if Learn
is misbehaving, please direct your bug report to bugs@learn.co.

[Raising issues on GitHub][raise] should be reserved for problems with
the curriculum itself (doesn't work, throws a Ruby error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
