### ISSUE TITLE
Checkboxes on the Code Challenge are "uncheckable"

### ISSUE THREAD

**Issue by jrodden1** [learn-co-curriculum/truthiness-code-challenge#34]
See Attached GIF.  I'm unable to answer the code challenge; when I try to click on an answer, I am unable to do so. 

![uncheckable](https://user-images.githubusercontent.com/39208179/59210189-38f6bf80-8b6a-11e9-8b09-c46c5d971ad2.gif)

Chrome Version 74.0.3729.169
MacOS Mojave 10.14.4

**Comment by drakeltheryuujin** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.
It's possible that it was fixed with the update earlier in July.

As always, thanks for contributing! 💙
