### ISSUE TITLE
Question 4 incorrectly says 7 is an incorrect answer

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/truthiness-code-challenge#35]
`7` is a valid answer for question #4, as illustrated here:

```
2.5.3 :001 > def using_truthiness
2.5.3 :002?>   7 > 6 || 7
2.5.3 :003?>   end
 => :using_truthiness
2.5.3 :004 > using_truthiness
 => true
```

Both `7 > 6` and `7` should be considered correct.

**Comment by lizbur10** [comment]
Hey @ivalentine! It looks like this question has been changed so I'm closing this issue. 💙
