### ISSUE TITLE
Code challenges not evaluating

### ISSUE THREAD

**Issue by JoanBrownCS** [learn-co-curriculum/truthiness-code-challenge#6]
I love the embedded tests in the lesson pages. I had no problem with the quiz working on the previous lesson page about truthiness.
The blocks where you have to submit the code to have it evaluated is not working. It says in a big red bar at the top:
Response could not be evaluated. Please try again.
Thanks,
Joan

**Comment by AnnJohn** [comment]
Hi @JoanBrownCS sorry for the issue that you're having. Since this is a bug report could you file a bug report for this in Learn? Thanks 

Also if you use the Ask a Question tool, someone from our Instructor support team should get back to you.
