### ISSUE TITLE
Errors Prevent Quiz Completion

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/truthiness-code-challenge#7]
For both questions 1 and 2, the beginning of the description for the next question appears within the box for the fourth answer choices. For example, the fourth answer choice for question 1 is:

> 17
> Here we have a method, returning_false that uses both comparison and boolean operators.

This option should be selectable, since it is also a correct response to question 1, but it is not. 

The fourth answer choice for question 2 is:

> 103
> CODE CHALLENGE III
> Take a look at the method using_truthiness below.

Also, there are no answer choices for question 3 ("What value(s) for ? will make using_truthiness return false?"), making it impossible to complete the quiz. 

Question 4 seems to be working fine.

**Comment by AnnJohn** [comment]
this should be fixed now. Thanks.
