### ISSUE TITLE
Broken quiz

### ISSUE THREAD

**Issue by caleb-cox** [learn-co-curriculum/truthiness-code-challenge#8]
- The first question's fourth answer includes part of the text for the second question.

![screen shot 2016-06-07 at 5 49 04 pm](https://cloud.githubusercontent.com/assets/19765134/15875868/26005e52-2cd8-11e6-8345-fdb61c0ea823.png)
- The second question's fourth answer includes part of the text for the third question.

![screen shot 2016-06-07 at 5 49 28 pm](https://cloud.githubusercontent.com/assets/19765134/15875887/3d4e461e-2cd8-11e6-8240-1090b14d28c1.png)
- The third question has no answers available for selection.

![screen shot 2016-06-07 at 5 52 46 pm](https://cloud.githubusercontent.com/assets/19765134/15875969/ab7f614a-2cd8-11e6-9d19-7e668f8d84f6.png)
- Completion of the three available questions (skipping the third) is not sufficient to trigger the 'Complete Quiz' status, meaning this lesson is not currently possible to complete.

![screen shot 2016-06-07 at 5 53 06 pm](https://cloud.githubusercontent.com/assets/19765134/15875982/b761b7d8-2cd8-11e6-999c-70ae8073c33f.png)

**Comment by AnnJohn** [comment]
this should be fixed now. Thanks.
