### ISSUE TITLE
Unable to Move Forward Error

### ISSUE THREAD

**Issue by wildcatblue** [learn-co-curriculum/truthiness-code-challenge#9]
I answered the quiz questions on this page (as seen in the images below), but the right column does not turn green for me. 

Perhaps it's because there was not really a question in the space for question 3?

![screen shot 2016-06-08 at 4 05 08 pm](https://cloud.githubusercontent.com/assets/15336602/15885587/2477e2a6-2d93-11e6-9e1b-427883dad3cf.png)

![screen shot 2016-06-08 at 4 05 17 pm](https://cloud.githubusercontent.com/assets/15336602/15885594/3061891e-2d93-11e6-8310-100f667ce140.png)

![screen shot 2016-06-08 at 4 05 25 pm](https://cloud.githubusercontent.com/assets/15336602/15885602/35742e98-2d93-11e6-9d8f-138b4fc9f41d.png)

![screen shot 2016-06-08 at 4 05 48 pm](https://cloud.githubusercontent.com/assets/15336602/15885604/3841f8a8-2d93-11e6-8c3d-01cd4542fbc0.png)

**Comment by AnnJohn** [comment]
this should be fixed now. Thanks.
